/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago.patterns;

import org.schabi.newpipe.extractor.timeago.PatternsHolder;

public class iw extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
                        SECONDS  /**/ = {"שניות", "שנייה"},
            MINUTES  /**/ = {"דקה", "דקות"},
            HOURS    /**/ = {"שעה", "שעות", "2"},
            DAYS     /**/ = {"יום", "ימים", "2"},
            WEEKS    /**/ = {"שבוע", "שבועות", "2"},
            MONTHS   /**/ = {"חודש", "חודשים", "2"},
            YEARS    /**/ = {"שנה", "שנים", "2"};

    private static final iw INSTANCE = new iw();

    public static iw getInstance() {
        return INSTANCE;
    }

    private iw() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}